### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by Dilschat** [EGA-archive/ega-dataedge#6]
I've tried to run this project, but I can't compile it, because dependency:
 <dependency>
            <groupId>eu.elixir.ega.ebi</groupId>
            <artifactId>ega-htsjdk</artifactId>
            <version>1.0-SNAPSHOT</version>
 </dependency>
This dependency is not found. Maybe this repo is accessible only in ebi or there are any other restrictions why I cant get it.

**Comment by Dilschat** [comment]
![image](https://user-images.githubusercontent.com/25724742/41430038-96ee76ba-7017-11e8-8b17-863ad066808e.png)

Yeah, I suppose it is not available.

**Comment by AlexanderSenf** [comment]
It is here: https://github.com/EGA-archive/ega-htsjdk - for now it needs to be installed manually in the local Maven repo
